# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jaribio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jaribio.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6200f2f6bbc94b4f800558118f1fbf12 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_20e31cc35c434893906b4a2b36701f92 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jaribio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6200f2f6bbc94b4f800558118f1fbf12 }}/jaribio/jaribio:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jaribio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6966d5907cfa4aa99b7e9afcce96e838 }}
        images: 'jaribio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6200f2f6bbc94b4f800558118f1fbf12 }}/jaribio/jaribio:${{ github.sha }}'